#!/bin/bash

# Define ASCII art in purple
purple="\e[0;35m"
alt="\e[0;36m"
reset="\e[0m"

ascii_art="${purple}

    ███╗   ██╗███████╗██████╗ ██╗   ██╗██╗      █████╗
    ████╗  ██║██╔════╝██╔══██╗██║   ██║██║     ██╔══██╗
    ██╔██╗ ██║█████╗  ██████╔╝██║   ██║██║     ███████║
    ██║╚██╗██║██╔══╝  ██╔══██╗██║   ██║██║     ██╔══██║
    ██║ ╚████║███████╗██████╔╝╚██████╔╝███████╗██║  ██║
    ╚═╝  ╚═══╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝
    v1.0
${reset}"

# Function to display the main menu
display_menu() {
    clear
    echo -e "$ascii_art"
    echo -e "${alt}Current Working Directory: $(pwd)${reset}"
    echo -e "What would you like to do today?\n"
    echo "[0]: Exit"
    echo "[1]: Install Syati + Dependencies"
    echo -e ""
}

display_menu

read -p "=> " choice

echo "wait a sec"

